<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(MelonDir)/Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnityEngine.CoreModule\UnityEngine.CoreModule.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
